### ISSUE TITLE
Stopped changing the Minimum Version

### ISSUE THREAD

**Issue by jbs31047** [deadlydog/AutoUpdateProjectsMinimumRequiredClickOnceVersion#2] opened 2020-02-17 14:09 UTC
The script seems to work at least once then it stops updating the minimum required version for unknown reasons.

Using VS2019 & Windows 10

**Comment by deadlydog** [comment] 2020-02-17 15:38
Hmmmm, that's strange that it would work once and then stop. A bit more info would be help me troubleshoot your issue easier.

Questions:
- Are any errors reported in the Visual Studio Output window?
- Is it a regular .Net Framework project, or a .Net Core project?
- Are you using the NuGet package to install it? 
- Do you see the same problem occur if you create a brand new vanilla project?
- Are you building via Visual Studio or a build server?

Thanks!

**Comment by jbs31047** [comment] 2020-02-17 16:34
- See the Build Output below. It says it changed the Minimum Required Version from 1.0.0.8 - 1.0.0.9 but it did not.
- .net Framework
- Nuget Package - Version 1.5.4
- This is a fairly new project
- Visual Studio Build

===========================================================
1>------ Build started: Project: DispatchTracker, Configuration: Debug Any CPU ------
1>C:\Users\Codestalker\Documents\Visual Studio Projects\DispatchTracker\DispatchTracker\RadMainForm.cs(47,30,47,32): warning CS0168: The variable 'ex' is declared but never used
1>  DispatchTracker -> C:\Users\Codestalker\Documents\Visual Studio Projects\DispatchTracker\DispatchTracker\bin\Debug\DispatchTracker.exe
1>EXEC : warning : [string]The term 'tf.exe' is not recognized as the name of a cmdlet, function, script file, or operable
1>  program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
1>  & : The term 'tf.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
1>  spelling of the name, or if a path was included, verify that the path is correct and try again.
1>  At C:\Users\jbs31047\Documents\Visual Studio 
1>  Projects\DispatchTracker\DispatchTracker\PostBuildScripts\AutoUpdateProjectsMinimumRequiredClickOnceVersion.ps1:235 
1>  char:8
1>  +             { & "$TfPath" checkout "$Path" }
1>  +                 ~~~~~~~~~
1>      + CategoryInfo          : ObjectNotFound: (tf.exe:String) [], CommandNotFoundException
1>      + FullyQualifiedErrorId : CommandNotFoundException
1>   
1>  Updated Minimum Required Version of 'C:\Users\jbs31047\Documents\Visual Studio Projects\DispatchTracker\DispatchTracker\DispatchTracker.csproj' from '1.0.0.8' to '1.0.0.9'
Building DispatchTracker...
2>------ Publish started: Project: DispatchTracker, Configuration: Debug Any CPU ------
Connecting to 'ftp://SupplyChain/DispatchTracker/'...
Publishing files...
Publish success.
http://supplychain/AppPublishing/DispatchTracker/publish.htm
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by deadlydog** [comment] 2020-03-05 18:42
Thanks for the info @jbs31047 . It looks like the issue may be that it can't find the `tf.exe`; although that may just be a red herring. I've pushed up a new v1.0.8 version of the NuGet package, as well as updated the docs on the project homepage. Can you take a look and give it another shot with the new version please.

I'm using VS 2019 and Windows 10 as well and created a new project and everything worked as expected.

If the problem persists, are you using the `package.config` style of NuGet in your project, or the package reference format?

Thanks!

**Comment by arteny** [comment] 2020-10-24 21:21
Nothing changing according to the version at all for me after build for .NET 4.6.1 project 
"As you can see in the last screenshot, it adds a new "PostBuildScripts" folder to your project that contains the PowerShell script that is ran from the project’s post-build event."
But no any such folder created when installing the package.

**Comment by deadlydog** [comment] 2022-12-23 04:25
Hey @arteny , your issue is different than this one, and I haven't been able to reproduce the issue. I've updated the ReadMe docs to show how to manually install the script though (for .NET Core projects), so you can follow that if you are still having the issue.

I'm going to close this issue since I've been waiting for more info for a couple years and am still unable to reproduce this problem. If you have more information @jbs31047 , feel free to reopen this.

**Closed as completed by deadlydog** 2022-12-23 04:25 UTC
Labels: need more info
